1450167578175	Sync.Service	INFO	Loading Weave 1.44.0
1450167578178	Sync.Engine.Clients	DEBUG	Engine initialized
1450167578180	Sync.Engine.Clients	DEBUG	Resetting clients last sync time
1450167578188	Sync.Engine.Bookmarks	DEBUG	Engine initialized
1450167578193	Sync.Engine.Forms	DEBUG	Engine initialized
1450167578198	Sync.Engine.History	DEBUG	Engine initialized
1450167578204	Sync.Engine.Passwords	DEBUG	Engine initialized
1450167578208	Sync.Engine.Prefs	DEBUG	Engine initialized
1450167578212	Sync.Engine.Tabs	DEBUG	Engine initialized
1450167578213	Sync.Engine.Tabs	DEBUG	Resetting tabs last sync time
1450167578220	Sync.Engine.Addons	DEBUG	Engine initialized
1450167578222	Sync.Service	INFO	Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:42.0) Gecko/20100101 Firefox/42.0
1450167578227	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1450167578228	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1450167578229	Sync.Service	DEBUG	Caching URLs under storage user base: https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/
1450167578229	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1450167578229	Sync.AddonsReconciler	INFO	Registering as Add-on Manager listener.
1450167578229	Sync.AddonsReconciler	DEBUG	Adding change listener.
1450167578230	Sync.Tracker.History	INFO	Adding Places observer.
1450167578233	FirefoxAccounts	DEBUG	got keyPair
1450167578234	FirefoxAccounts	DEBUG	getCertificateSigned: true true
1450167578276	browserwindow.syncui	DEBUG	observed: weave:service:ready
1450167578278	browserwindow.syncui	DEBUG	_loginFailed has sync state=success.login
1450167578280	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1450167578281	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1450167578823	Hawk	DEBUG	(Response) /certificate/sign: code: 200 - Status text: OK
1450167578824	Sync.RESTResponse	TRACE	Processing response headers.
1450167578825	Hawk	DEBUG	Clock offset vs https://api.accounts.firefox.com/v1: -824
1450167578825	FirefoxAccounts	DEBUG	getCertificate got a new one: true
1450167578826	FirefoxAccounts	DEBUG	_updateAccountData with items: ["keyPair","cert"]
1450167578827	FirefoxAccounts	DEBUG	getAssertionFromCert
1450167578828	FirefoxAccounts	DEBUG	writing plain storage: ["email","sessionToken","uid","verified","oauthTokens"]
1450167578828	FirefoxAccounts	TRACE	starting write of json user data: ["email","sessionToken","uid","verified","oauthTokens"]
1450167578834	FirefoxAccounts	DEBUG	getAssertionFromCert returning signed: true
1450167578835	Sync.BrowserIDManager	DEBUG	Getting a token
1450167578836	Common.TokenServerClient	DEBUG	Beginning BID assertion exchange: https://token.services.mozilla.com/1.0/sync/1.5
1450167578841	FirefoxAccounts	TRACE	finished write of json user data - took: 13
1450167578842	FirefoxAccounts	DEBUG	writing secure storage: ["kA","kB"]
1450167578842	FirefoxAccounts	TRACE	starting write of user data to the login manager
1450167578853	FirefoxAccounts	TRACE	finished write of user data to the login manager
1450167579434	Common.TokenServerClient	DEBUG	Got token response: 200
1450167579434	Sync.RESTResponse	TRACE	Processing response headers.
1450167579434	Common.TokenServerClient	DEBUG	Successful token response
1450167579434	Sync.BrowserIDManager	DEBUG	Successfully got a sync token
1450167579436	Sync.BulkKeyBundle	INFO	BulkKeyBundle being created for undefined
1450167579436	Sync.BrowserIDManager	INFO	Background fetch for key bundle done
1450167579436	Sync.Status	DEBUG	Status.login: success.login => success.login
1450167579436	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1450167584280	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1450167584281	Sync.Service	DEBUG	User-Agent: Firefox/42.0 FxSync/1.44.0.20151030084423.
1450167584281	Sync.Service	INFO	Starting sync at 2015-12-15 09:19:44
1450167584281	Sync.Service	DEBUG	In sync: should login.
1450167584282	browserwindow.syncui	DEBUG	observed: weave:service:login:start
1450167584282	browserwindow.syncui	DEBUG	onActivityStart with numActive: 0
1450167584282	browserwindow.syncui	DEBUG	_loginFailed has sync state=success.login
1450167584282	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1450167584282	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1450167584283	Sync.Service	INFO	Logging in the user.
1450167584283	Sync.Service	DEBUG	Caching URLs under storage user base: https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/
1450167584284	Sync.BrowserIDManager	DEBUG	unlockAndVerifyAuthState already has (or can fetch) sync keys
1450167584284	Sync.Service	DEBUG	Fetching unlocked auth state returned success.status_ok
1450167584285	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
1450167584670	Sync.SyncScheduler	DEBUG	Next sync in 90000 ms.
1450167584864	Sync.Resource	DEBUG	mesg: GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/info/collections
1450167584864	Sync.Resource	DEBUG	GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/info/collections
1450167584864	Sync.Service	DEBUG	Fetching global metadata record
1450167584865	Sync.RecordManager	TRACE	Importing record: https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/meta/global
1450167584865	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
1450167585038	Sync.Resource	DEBUG	mesg: GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/meta/global
1450167585038	Sync.Resource	DEBUG	GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/meta/global
1450167585039	Sync.Service	DEBUG	Clearing cached meta record. metaModified is undefined, setting to 1437323829.93
1450167585039	Sync.RecordManager	TRACE	Importing record: https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/meta/global
1450167585040	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
1450167585231	Sync.Resource	DEBUG	mesg: GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/meta/global
1450167585231	Sync.Resource	DEBUG	GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/meta/global
1450167585231	Sync.Service	DEBUG	Weave Version: 1.44.0 Local Storage: 5 Remote Storage: 5
1450167585232	Sync.Service	INFO	Sync key is up-to-date: no need to upgrade.
1450167585232	Sync.Service	DEBUG	Fetching and verifying -- or generating -- symmetric keys.
1450167585232	Sync.Service	INFO	Testing info/collections: {"passwords":1450167497.4,"addons":1450167121.19,"tabs":1450167497.81,"clients":1450167495.5,"crypto":1437323809.75,"forms":1450167536.58,"meta":1437323829.93,"bookmarks":1450167500.61,"prefs":1450167496.22,"history":1450104774.12}
1450167585232	Sync.CollectionKeyManager	INFO	Testing for updateNeeded. Last modified: 0
1450167585232	Sync.Service	INFO	collection keys reports that a key update is needed.
1450167585233	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
1450167585427	Sync.Resource	DEBUG	mesg: GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/crypto/keys
1450167585427	Sync.Resource	DEBUG	GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/crypto/keys
1450167585428	Sync.CollectionKeyManager	INFO	Updating collection keys...
1450167585430	Sync.CollectionKeyManager	INFO	Setting collection keys contents. Our last modified: 0, input modified: 1437323809.75.
1450167585430	Sync.BulkKeyBundle	INFO	BulkKeyBundle being created for [default]
1450167585430	Sync.CollectionKeyManager	INFO	Processing downloaded per-collection keys.
1450167585430	Sync.CollectionKeyManager	INFO	Clearing collection keys...
1450167585430	Sync.CollectionKeyManager	INFO	Saving downloaded keys.
1450167585430	Sync.CollectionKeyManager	INFO	Bumping last modified to 1437323809.75
1450167585430	Sync.CollectionKeyManager	INFO	Collection keys updated.
1450167585430	Sync.Status	DEBUG	Status.login: success.login => success.login
1450167585430	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1450167585431	browserwindow.syncui	DEBUG	observed: weave:service:login:finish
1450167585431	browserwindow.syncui	DEBUG	onActivityStop with numActive: 1
1450167585431	browserwindow.syncui	DEBUG	_loginFailed has sync state=success.login
1450167585433	browserwindow.syncui	DEBUG	observed: weave:service:sync:start
1450167585433	browserwindow.syncui	DEBUG	onActivityStart with numActive: 0
1450167585433	browserwindow.syncui	DEBUG	_loginFailed has sync state=success.login
1450167585434	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1450167585435	Sync.Status	INFO	Resetting Status.
1450167585435	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1450167585436	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
1450167585614	Sync.Resource	DEBUG	mesg: GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/info/collections
1450167585614	Sync.Resource	DEBUG	GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/info/collections
1450167585615	Sync.Service	DEBUG	Fetching global metadata record
1450167585615	Sync.Service	DEBUG	Weave Version: 1.44.0 Local Storage: 5 Remote Storage: 5
1450167585616	Sync.Service	INFO	Sync key is up-to-date: no need to upgrade.
1450167585616	Sync.Service	DEBUG	Fetching and verifying -- or generating -- symmetric keys.
1450167585616	Sync.Service	INFO	Testing info/collections: {"passwords":1450167497.4,"addons":1450167121.19,"tabs":1450167497.81,"clients":1450167495.5,"crypto":1437323809.75,"forms":1450167536.58,"meta":1437323829.93,"bookmarks":1450167500.61,"prefs":1450167496.22,"history":1450104774.12}
1450167585616	Sync.CollectionKeyManager	INFO	Testing for updateNeeded. Last modified: 1437323809.75
1450167585616	Sync.Synchronizer	DEBUG	Refreshing client list.
1450167585617	Sync.Engine.Clients	DEBUG	First sync, uploading all items
1450167585617	Sync.Engine.Clients	INFO	1 outgoing items pre-reconciliation
1450167585619	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
1450167585835	Sync.Collection	DEBUG	mesg: GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/clients?full=1
1450167585835	Sync.Collection	DEBUG	GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/clients?full=1
1450167585837	Sync.Engine.Clients	INFO	Records: 14 applied, 14 successfully, 0 failed to apply, 0 newly failed to apply, 0 reconciled.
1450167585839	Sync.Engine.Clients	INFO	Uploading all of 1 records
1450167585840	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
1450167585841	Sync.Collection	DEBUG	POST Length: 465
1450167586076	Sync.Collection	DEBUG	mesg: POST success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/clients
1450167586076	Sync.Collection	DEBUG	POST success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/clients
1450167586078	Sync.Synchronizer	INFO	Updating enabled engines: 14 clients.
1450167586081	Sync.Engine.Prefs	INFO	1 outgoing items pre-reconciliation
1450167586083	Sync.Engine.Prefs	INFO	Records: 0 applied, 0 successfully, 0 failed to apply, 0 newly failed to apply, 0 reconciled.
1450167586105	Sync.Engine.Prefs	INFO	Uploading all of 1 records
1450167586105	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
1450167586107	Sync.Collection	DEBUG	POST Length: 11711
1450167586319	Sync.Collection	DEBUG	mesg: POST success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/prefs
1450167586319	Sync.Collection	DEBUG	POST success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/prefs
1450167586321	Sync.Engine.Passwords	INFO	0 outgoing items pre-reconciliation
1450167586323	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
1450167586504	Sync.Collection	DEBUG	mesg: GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/passwords?newer=1450166790.08&full=1
1450167586504	Sync.Collection	DEBUG	GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/passwords?newer=1450166790.08&full=1
1450167586505	Sync.Engine.Passwords	INFO	Records: 0 applied, 0 successfully, 0 failed to apply, 0 newly failed to apply, 0 reconciled.
1450167586506	Sync.Engine.Tabs	DEBUG	First sync, uploading all items
1450167586507	Sync.Engine.Tabs	INFO	1 outgoing items pre-reconciliation
1450167586509	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
1450167586617	Sync.Tracker.Clients	DEBUG	Saving changed IDs to clients
1450167586685	Sync.Store.Tabs	DEBUG	Adding remote tabs from agis Firefox auf be15
1450167586687	Sync.Store.Tabs	DEBUG	Adding remote tabs from agis Firefox auf be15
1450167586694	Sync.Store.Tabs	DEBUG	Adding remote tabs from christians Firefox auf O2-10-PC02
1450167586695	Sync.Store.Tabs	DEBUG	Adding remote tabs from Christian's Nightly on PC-Christian
1450167586696	Sync.Store.Tabs	DEBUG	Adding remote tabs from agis Firefox auf be15
1450167586698	Sync.Store.Tabs	DEBUG	Adding remote tabs from Sonjas Firefox auf Privat-PC
1450167586706	Sync.Store.Tabs	DEBUG	Adding remote tabs from tschriss Firefox auf fog01
1450167586706	Sync.Collection	DEBUG	mesg: GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/tabs?full=1
1450167586706	Sync.Collection	DEBUG	GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/tabs?full=1
1450167586707	Sync.Engine.Tabs	INFO	Records: 7 applied, 7 successfully, 0 failed to apply, 0 newly failed to apply, 1 reconciled.
1450167586714	Sync.Engine.Tabs	INFO	Uploading all of 1 records
1450167586715	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
1450167586718	Sync.Collection	DEBUG	POST Length: 420
1450167586892	Sync.Collection	DEBUG	mesg: POST success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/tabs
1450167586892	Sync.Collection	DEBUG	POST success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/tabs
1450167586898	Sync.Engine.Bookmarks	INFO	0 outgoing items pre-reconciliation
1450167586903	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
1450167587077	Sync.Collection	DEBUG	mesg: GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/bookmarks?newer=1450167500.39&full=1&sort=index
1450167587077	Sync.Collection	DEBUG	GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/bookmarks?newer=1450167500.39&full=1&sort=index
1450167587078	Sync.Engine.Bookmarks	INFO	Records: 0 applied, 0 successfully, 0 failed to apply, 0 newly failed to apply, 0 reconciled.
1450167587080	Sync.Engine.Addons	DEBUG	Refreshing reconciler state
1450167587080	Sync.AddonsReconciler	INFO	Refreshing global state from AddonManager.
1450167587093	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: {972ce4c6-7e08-4474-a285-3208198ce6fd}
1450167587093	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: langpack-de@firefox.mozilla.org
1450167587093	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: langpack-en-GB@firefox.mozilla.org
1450167587094	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: langpack-en-ZA@firefox.mozilla.org
1450167587094	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: ubufox@ubuntu.com
1450167587094	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: {d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
1450167587094	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: {dd3d7613-0246-469d-bc65-2a3cc1668adc}
1450167587094	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: {b9db16a4-6edc-47ec-a1f4-b86292ed211d}
1450167587094	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: info@youtube-mp3.org
1450167587094	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: {a7c6cf7f-112c-4500-a7ea-39801a327e5f}
1450167587094	Sync.AddonsReconciler	DEBUG	Adding change because enabled state changed: {a7c6cf7f-112c-4500-a7ea-39801a327e5f}
1450167587094	Sync.AddonsReconciler	INFO	Change recorded for {a7c6cf7f-112c-4500-a7ea-39801a327e5f}
1450167587095	Sync.Tracker.Addons	DEBUG	changeListener invoked: 4 {a7c6cf7f-112c-4500-a7ea-39801a327e5f}
1450167587096	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: {9BAE5926-8513-417d-8E47-774955A7C60D}
1450167587097	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: {5384767E-00D9-40E9-B72F-9CC39D655D6F}
1450167587097	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: {02450914-cdd9-410f-b1da-db004e18c671}
1450167587097	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: 666536@personas.mozilla.org
1450167587097	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: recommended-5@personas.mozilla.org
1450167587097	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: recommended-2@personas.mozilla.org
1450167587098	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: gmp-gmpopenh264
1450167587098	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: {87f4b7ec-48da-8a55-77c4-410d1d063657}
1450167587098	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: {60c47189-8c9a-b46e-fa2f-63783ef86c9e}
1450167587105	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: {bfef53c5-81c2-0178-4bf8-c69c0b4c4614}
1450167587107	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: {cb7b6e93-283b-b6c7-7750-9c03196fcdd8}
1450167587109	Sync.AddonsReconciler	INFO	Saving reconciler state to file: addonsreconciler
1450167587116	Sync.Store.Addons	DEBUG	666536@personas.mozilla.org not syncable: add-on not found in add-on repository.
1450167587116	Sync.Store.Addons	DEBUG	{972ce4c6-7e08-4474-a285-3208198ce6fd} not syncable: not installed in profile.
1450167587117	Sync.Store.Addons	DEBUG	666536@personas.mozilla.org not syncable: add-on not found in add-on repository.
1450167587117	Sync.Store.Addons	DEBUG	langpack-de@firefox.mozilla.org not syncable: type not in whitelist: locale
1450167587117	Sync.Store.Addons	DEBUG	langpack-en-GB@firefox.mozilla.org not syncable: type not in whitelist: locale
1450167587117	Sync.Store.Addons	DEBUG	langpack-en-ZA@firefox.mozilla.org not syncable: type not in whitelist: locale
1450167587117	Sync.Store.Addons	DEBUG	ubufox@ubuntu.com not syncable: not installed in profile.
1450167587118	Sync.Store.Addons	DEBUG	recommended-5@personas.mozilla.org not syncable: add-on not found in add-on repository.
1450167587118	Sync.Store.Addons	DEBUG	recommended-2@personas.mozilla.org not syncable: add-on not found in add-on repository.
1450167587118	Sync.Store.Addons	DEBUG	gmp-gmpopenh264 not syncable: type not in whitelist: plugin
1450167587118	Sync.Store.Addons	DEBUG	{87f4b7ec-48da-8a55-77c4-410d1d063657} not syncable: type not in whitelist: plugin
1450167587118	Sync.Store.Addons	DEBUG	{60c47189-8c9a-b46e-fa2f-63783ef86c9e} not syncable: type not in whitelist: plugin
1450167587118	Sync.Store.Addons	DEBUG	{bfef53c5-81c2-0178-4bf8-c69c0b4c4614} not syncable: type not in whitelist: plugin
1450167587118	Sync.Store.Addons	DEBUG	{cb7b6e93-283b-b6c7-7750-9c03196fcdd8} not syncable: type not in whitelist: plugin
1450167587119	Sync.Engine.Addons	DEBUG	Adding changed add-on from changes log: {9BAE5926-8513-417d-8E47-774955A7C60D}
1450167587119	Sync.Engine.Addons	DEBUG	Adding changed add-on from changes log: {d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
1450167587120	Sync.Engine.Addons	DEBUG	Adding changed add-on from changes log: {dd3d7613-0246-469d-bc65-2a3cc1668adc}
1450167587120	Sync.Engine.Addons	DEBUG	Adding changed add-on from changes log: {b9db16a4-6edc-47ec-a1f4-b86292ed211d}
1450167587120	Sync.Engine.Addons	DEBUG	Adding changed add-on from changes log: info@youtube-mp3.org
1450167587121	Sync.Engine.Addons	DEBUG	Adding changed add-on from changes log: {02450914-cdd9-410f-b1da-db004e18c671}
1450167587121	Sync.Store.Addons	DEBUG	gmp-gmpopenh264 not syncable: type not in whitelist: plugin
1450167587121	Sync.Engine.Addons	DEBUG	Adding changed add-on from changes log: {5384767E-00D9-40E9-B72F-9CC39D655D6F}
1450167587121	Sync.Engine.Addons	DEBUG	Adding changed add-on from changes log: {a7c6cf7f-112c-4500-a7ea-39801a327e5f}
1450167587122	Sync.Engine.Addons	DEBUG	Adding changed add-on from changes log: {a7c6cf7f-112c-4500-a7ea-39801a327e5f}
1450167587122	Sync.Engine.Addons	DEBUG	Adding changed add-on from changes log: {a7c6cf7f-112c-4500-a7ea-39801a327e5f}
1450167587122	Sync.Engine.Addons	INFO	10 outgoing items pre-reconciliation
1450167587125	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
1450167587133	Sync.Engine.Addons	ERROR	null
1450167587199	Sync.SyncScheduler	DEBUG	Global Score threshold hit, triggering sync.
1450167587199	Sync.Service	DEBUG	User-Agent: Firefox/42.0 FxSync/1.44.0.20151030084423.
1450167587199	Sync.Service	INFO	Starting sync at 2015-12-15 09:19:47
1450167587199	Sync.Service	DEBUG	Exception: Could not acquire lock. Label: "service.js: sync". No traceback available
1450167587199	Sync.Service	INFO	Cannot start sync: already syncing?
1450167587322	Sync.Tracker.Passwords	DEBUG	Saving changed IDs to passwords
1450167587345	Sync.Engine.Addons	DEBUG	Switching local ID to incoming: vm-ymXQ5Ic4E -> 72b4rWjXzC5K
1450167587346	Sync.AddonsReconciler	INFO	Saving reconciler state to file: addonsreconciler
1450167587356	Sync.Engine.Addons	DEBUG	Local item after duplication: age=0.26199984550476074; modified=true; exists=true
1450167587709	Sync.SyncScheduler	DEBUG	Global Score threshold hit, triggering sync.
1450167587710	Sync.Service	DEBUG	User-Agent: Firefox/42.0 FxSync/1.44.0.20151030084423.
1450167587710	Sync.Service	INFO	Starting sync at 2015-12-15 09:19:47
1450167587710	Sync.Service	DEBUG	Exception: Could not acquire lock. Label: "service.js: sync". No traceback available
1450167587710	Sync.Service	INFO	Cannot start sync: already syncing?
1450167587898	Sync.Tracker.Bookmarks	DEBUG	Saving changed IDs to bookmarks
1450167588122	Sync.Tracker.Addons	DEBUG	Saving changed IDs to addons
1450167588520	Sync.SyncScheduler	DEBUG	Global Score threshold hit, triggering sync.
1450167588522	Sync.Service	DEBUG	User-Agent: Firefox/42.0 FxSync/1.44.0.20151030084423.
1450167588522	Sync.Service	INFO	Starting sync at 2015-12-15 09:19:48
1450167588522	Sync.Service	DEBUG	Exception: Could not acquire lock. Label: "service.js: sync". No traceback available
1450167588522	Sync.Service	INFO	Cannot start sync: already syncing?
1450167589184	Sync.AddonUtils	INFO	Found 0/1 add-ons during repository search.
1450167589185	Sync.Store.Addons	WARN	Failed to apply incoming record GFwMvbBsMs8n
1450167589186	Sync.Store.Addons	WARN	Encountered exception: Error: Add-on not found after install: {5F4EC95A-FFA8-11DE-898C-667D55D89593} (resource://gre/modules/services-sync/engines/addons.js:311:1) JS Stack trace: create@addons.js:311:1 < Store.prototype.applyIncoming@engines.js:336:7 < applyIncoming@addons.js:281:5 < Store.prototype.applyIncomingBatch@engines.js:304:9 < doApplyBatch@engines.js:994:32 < SyncEngine.prototype._processIncoming/newitems.recordHandler@engines.js:1105:9 < Collection.prototype.recordHandler/this._onProgress@record.js:624:9 < Channel_onDataAvail@resource.js:558:7 < waitForSyncCallback@async.js:102:7 < Res__request@resource.js:405:14 < Res_get@resource.js:429:12 < SyncEngine.prototype._processIncoming@engines.js:1168:18 < SyncEngine.prototype._sync@engines.js:1524:7 < WrappedNotify@util.js:148:21 < Engine.prototype.sync@engines.js:668:5 < _syncEngine@enginesync.js:199:7 < sync@enginesync.js:149:15 < onNotify@service.js:1304:7 < WrappedNotify@util.js:148:21 < WrappedLock@util.js:103:16 < _lockedSync@service.js:1294:12 < sync/<@service.js:1286:14 < WrappedCatch@util.js:77:16 < sync@service.js:1274:5
1450167589187	Sync.Collection	DEBUG	mesg: GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/addons?full=1&ids=72b4rWjXzC5K,GFwMvbBsMs8n
1450167589187	Sync.Collection	DEBUG	GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/addons?full=1&ids=72b4rWjXzC5K,GFwMvbBsMs8n
1450167589188	Sync.Engine.Addons	DEBUG	Records that failed to apply: GFwMvbBsMs8n
1450167589188	Sync.Engine.Addons	INFO	Records: 1 applied, 0 successfully, 1 failed to apply, 0 newly failed to apply, 1 reconciled.
1450167589205	Sync.Engine.Addons	ERROR	null
1450167589213	Sync.Engine.Addons	INFO	Uploading all of 8 records
1450167589214	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
1450167589217	Sync.Collection	DEBUG	POST Length: 3199
1450167589439	Sync.Collection	DEBUG	mesg: POST success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/addons
1450167589439	Sync.Collection	DEBUG	POST success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/addons
1450167589441	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
1450167589652	Sync.Collection	DEBUG	mesg: DELETE success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/addons?ids=vm-ymXQ5Ic4E
1450167589652	Sync.Collection	DEBUG	DELETE success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/addons?ids=vm-ymXQ5Ic4E
1450167589654	Sync.Engine.Forms	INFO	0 outgoing items pre-reconciliation
1450167589655	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
1450167589846	Sync.Collection	DEBUG	mesg: GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/forms?newer=1450167121.61&full=1
1450167589846	Sync.Collection	DEBUG	GET success 200 https://sync-231-us-west-2.sync.services.mozilla.com/1.5/25611844/storage/forms?newer=1450167121.61&full=1
1450167589847	Sync.Engine.Forms	INFO	Records: 0 applied, 0 successfully, 0 failed to apply, 0 newly failed to apply, 0 reconciled.
1450167589849	Sync.Engine.History	DEBUG	First sync, uploading all items
1450167590002	Sync.Engine.History	INFO	399 outgoing items pre-reconciliation
1450167590004	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
1450167590300	Sync.SyncScheduler	DEBUG	Global Score threshold hit, triggering sync.
1450167590300	Sync.Service	DEBUG	User-Agent: Firefox/42.0 FxSync/1.44.0.20151030084423.
1450167590300	Sync.Service	INFO	Starting sync at 2015-12-15 09:19:50
1450167590300	Sync.Service	DEBUG	Exception: Could not acquire lock. Label: "service.js: sync". No traceback available
1450167590300	Sync.Service	INFO	Cannot start sync: already syncing?
1450167590654	Sync.Tracker.Forms	DEBUG	Saving changed IDs to forms
1450167591003	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1450167591213	Sync.Engine.History	WARN	DATA LOSS: Both local and remote changes to record: 8CMB5AknmGBO
1450167596350	Sync.AddonsReconciler	DEBUG	Add-on change: onEnabling to {a7c6cf7f-112c-4500-a7ea-39801a327e5f}
1450167596350	Sync.AddonsReconciler	DEBUG	Rectifying state for addon: {a7c6cf7f-112c-4500-a7ea-39801a327e5f}
1450167596350	Sync.AddonsReconciler	DEBUG	Adding change because enabled state changed: {a7c6cf7f-112c-4500-a7ea-39801a327e5f}
1450167596350	Sync.AddonsReconciler	INFO	Change recorded for {a7c6cf7f-112c-4500-a7ea-39801a327e5f}
1450167596350	Sync.Tracker.Addons	DEBUG	changeListener invoked: 3 {a7c6cf7f-112c-4500-a7ea-39801a327e5f}
1450167596354	Sync.AddonsReconciler	INFO	Saving reconciler state to file: addonsreconciler
1450167597116	Sync.SyncScheduler	DEBUG	Global Score threshold hit, triggering sync.
1450167597199	Sync.Service	DEBUG	User-Agent: Firefox/42.0 FxSync/1.44.0.20151030084423.
1450167597199	Sync.Service	INFO	Starting sync at 2015-12-15 09:19:57
1450167597199	Sync.Service	DEBUG	Exception: Could not acquire lock. Label: "service.js: sync". No traceback available
1450167597199	Sync.Service	INFO	Cannot start sync: already syncing?
1450167597466	Sync.Tracker.Addons	DEBUG	Saving changed IDs to addons
1450167599628	Sync.Engine.History	WARN	Failed to reconcile incoming record Hi0z9nAodQSU
1450167599630	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599631	Sync.Engine.History	WARN	Failed to reconcile incoming record fmjn45LFaKFP
1450167599633	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599634	Sync.Engine.History	WARN	Failed to reconcile incoming record 5E9fHhmLuhvI
1450167599635	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599637	Sync.Engine.History	WARN	Failed to reconcile incoming record O8MlqMkGYDpO
1450167599638	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599639	Sync.Engine.History	WARN	Failed to reconcile incoming record Jw6OTES_dP7R
1450167599640	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599644	Sync.Engine.History	WARN	Failed to reconcile incoming record HXQVc3vaFK9Y
1450167599645	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599646	Sync.Engine.History	WARN	Failed to reconcile incoming record EUJaU6WrmcBX
1450167599647	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599648	Sync.Engine.History	WARN	Failed to reconcile incoming record 6wLjVMAUGagJ
1450167599650	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599651	Sync.Engine.History	WARN	Failed to reconcile incoming record 4HipQpDjP2nP
1450167599652	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599653	Sync.Engine.History	WARN	Failed to reconcile incoming record -Cn0dD3N_Ssi
1450167599654	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599655	Sync.Engine.History	WARN	Failed to reconcile incoming record zMO_w811Ph5M
1450167599657	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599658	Sync.Engine.History	WARN	Failed to reconcile incoming record s5mfcNoNpnGy
1450167599659	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599660	Sync.Engine.History	WARN	Failed to reconcile incoming record O0Hv_jNVWnqz
1450167599661	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599662	Sync.Engine.History	WARN	Failed to reconcile incoming record mgJdSRtK-Te7
1450167599664	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599665	Sync.Engine.History	WARN	Failed to reconcile incoming record gTvdCAoVbb5x
1450167599666	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599667	Sync.Engine.History	WARN	Failed to reconcile incoming record gs6buOVU1H51
1450167599668	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599669	Sync.Engine.History	WARN	Failed to reconcile incoming record cSNDef7UT5tC
1450167599670	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599671	Sync.Engine.History	WARN	Failed to reconcile incoming record 8lNovVpC7uUQ
1450167599673	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599674	Sync.Engine.History	WARN	Failed to reconcile incoming record y43kbmHsvXFM
1450167599675	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599676	Sync.Engine.History	WARN	Failed to reconcile incoming record WTa_JVi1si9m
1450167599677	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599679	Sync.Engine.History	WARN	Failed to reconcile incoming record UcCLjb6LJRfb
1450167599680	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599681	Sync.Engine.History	WARN	Failed to reconcile incoming record T_VZzeUQxO_y
1450167599682	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599683	Sync.Engine.History	WARN	Failed to reconcile incoming record RS-oTKCyg3Qj
1450167599685	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599685	Sync.Engine.History	WARN	Failed to reconcile incoming record Qyk0QaBLsOWo
1450167599687	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599688	Sync.Engine.History	WARN	Failed to reconcile incoming record QvAFZhhvjs5k
1450167599689	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599690	Sync.Engine.History	WARN	Failed to reconcile incoming record QjkFHkH8PIqM
1450167599691	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599692	Sync.Engine.History	WARN	Failed to reconcile incoming record pnaB5vXj_CU-
1450167599694	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599695	Sync.Engine.History	WARN	Failed to reconcile incoming record Odnnlhl4Ew9D
1450167599696	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599697	Sync.Engine.History	WARN	Failed to reconcile incoming record N1Z6p16_ykBE
1450167599698	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599699	Sync.Engine.History	WARN	Failed to reconcile incoming record LU0PKBOj5N85
1450167599701	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599702	Sync.Engine.History	WARN	Failed to reconcile incoming record LFYAcdfL4gJB
1450167599703	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599705	Sync.Engine.History	WARN	Failed to reconcile incoming record Jy1tAlVLRG8P
1450167599706	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599707	Sync.Engine.History	WARN	Failed to reconcile incoming record JERI9DQbluBY
1450167599708	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599709	Sync.Engine.History	WARN	Failed to reconcile incoming record JdPNcUZ0Vkk0
1450167599710	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599711	Sync.Engine.History	WARN	Failed to reconcile incoming record GTlS5o15GeB9
1450167599713	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599714	Sync.Engine.History	WARN	Failed to reconcile incoming record ehzYvpnrAXmx
1450167599715	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599716	Sync.Engine.History	WARN	Failed to reconcile incoming record DlT40qefaGpk
1450167599718	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599719	Sync.Engine.History	WARN	Failed to reconcile incoming record d57N9Sn1oX6q
1450167599720	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599721	Sync.Engine.History	WARN	Failed to reconcile incoming record D0U0C5L3EcCb
1450167599722	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599723	Sync.Engine.History	WARN	Failed to reconcile incoming record czwEe0SZAGG_
1450167599725	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599725	Sync.Engine.History	WARN	Failed to reconcile incoming record bcbQ6rgO2ogc
1450167599727	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599728	Sync.Engine.History	WARN	Failed to reconcile incoming record AFqeLIkePBMm
1450167599729	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599730	Sync.Engine.History	WARN	Failed to reconcile incoming record Aeo-FdKyYoJb
1450167599731	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599732	Sync.Engine.History	WARN	Failed to reconcile incoming record 9o9-yWoSSzfe
1450167599733	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599734	Sync.Engine.History	WARN	Failed to reconcile incoming record 9bqfB3w315oW
1450167599735	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599737	Sync.Engine.History	WARN	Failed to reconcile incoming record -_Ezsbx2o16Q
1450167599738	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599739	Sync.Engine.History	WARN	Failed to reconcile incoming record O5tfGTGtmU-5
1450167599740	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599741	Sync.Engine.History	WARN	Failed to reconcile incoming record fgKKDVZdklCZ
1450167599742	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599743	Sync.Engine.History	WARN	Failed to reconcile incoming record 2Tc_InKsjam6
1450167599744	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599746	Sync.Engine.History	WARN	Failed to reconcile incoming record v-3EBVcAq9dw
1450167599747	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599748	Sync.Engine.History	WARN	Failed to reconcile incoming record jzJ4sCzbKulP
1450167599749	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599750	Sync.Engine.History	WARN	Failed to reconcile incoming record IminqXdq62fF
1450167599751	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599752	Sync.Engine.History	WARN	Failed to reconcile incoming record FzevlHebbQ2c
1450167599753	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599755	Sync.Engine.History	WARN	Failed to reconcile incoming record c7zsnkHMgiQb
1450167599756	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599757	Sync.Engine.History	WARN	Failed to reconcile incoming record 0rJQZaDoBSvr
1450167599758	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599759	Sync.Engine.History	WARN	Failed to reconcile incoming record BQb5sV03Wk1n
1450167599760	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599761	Sync.Engine.History	WARN	Failed to reconcile incoming record Z02eB_q2TFo4
1450167599762	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599763	Sync.Engine.History	WARN	Failed to reconcile incoming record y5z5UJmTtgb9
1450167599764	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599765	Sync.Engine.History	WARN	Failed to reconcile incoming record xvbeR7-5gcYo
1450167599766	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599767	Sync.Engine.History	WARN	Failed to reconcile incoming record NYELCFO9eXWl
1450167599769	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599770	Sync.Engine.History	WARN	Failed to reconcile incoming record N4o4CWUXpwG-
1450167599771	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599772	Sync.Engine.History	WARN	Failed to reconcile incoming record hIWecB-09W0r
1450167599774	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599775	Sync.Engine.History	WARN	Failed to reconcile incoming record g47rkAw5G2x6
1450167599776	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599777	Sync.Engine.History	WARN	Failed to reconcile incoming record FL9IDF12Nb8v
1450167599778	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599779	Sync.Engine.History	WARN	Failed to reconcile incoming record EFJxvCR81g4R
1450167599780	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599781	Sync.Engine.History	WARN	Failed to reconcile incoming record cchQL71vG71v
1450167599782	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599783	Sync.Engine.History	WARN	Failed to reconcile incoming record AXhM_zD-25mM
1450167599785	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599785	Sync.Engine.History	WARN	Failed to reconcile incoming record 8TOITcBTb1ja
1450167599787	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599788	Sync.Engine.History	WARN	Failed to reconcile incoming record 4Siob-TWQQhz
1450167599789	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599790	Sync.Engine.History	WARN	Failed to reconcile incoming record 2N9KawOsPN9P
1450167599791	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599792	Sync.Engine.History	WARN	Failed to reconcile incoming record _2rckKryXqby
1450167599793	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599794	Sync.Engine.History	WARN	Failed to reconcile incoming record YOkRjOcBJfbx
1450167599795	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599796	Sync.Engine.History	WARN	Failed to reconcile incoming record xir3G15-Ha54
1450167599797	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599798	Sync.Engine.History	WARN	Failed to reconcile incoming record WXc9n_s2FVM1
1450167599800	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599801	Sync.Engine.History	WARN	Failed to reconcile incoming record WlWwnkxOExhY
1450167599802	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599803	Sync.Engine.History	WARN	Failed to reconcile incoming record wgBUgUT7Mm1g
1450167599804	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599805	Sync.Engine.History	WARN	Failed to reconcile incoming record UfWyPgaKVHKk
1450167599806	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599807	Sync.Engine.History	WARN	Failed to reconcile incoming record TSQtkvpKg6US
1450167599808	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599809	Sync.Engine.History	WARN	Failed to reconcile incoming record TMoROn86o9lN
1450167599810	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < waitForSyncCallback()@resource://services-common/async.js:102 < Res__request()@resource://services-sync/resource.js:405 < Res_get()@resource://services-sync/resource.js:429 < SyncEngine.prototype._processIncoming()@resource://services-sync/engines.js:1112 < SyncEngine.prototype._sync()@resource://services-sync/engines.js:1524 < WrappedNotify()@resource://services-sync/util.js:148 < Engine.prototype.sync()@resource://services-sync/engines.js:668 < _syncEngine()@resource://services-sync/stages/enginesync.js:199 < sync()@resource://services-sync/stages/enginesync.js:149 < onNotify()@resource://gre/modules/services-sync/service.js:1304 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167599811	Sync.Engine.History	WARN	Failed to reconcile incoming record sY2jlBJAEDPV
1450167599812	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engin